### ISSUE TITLE
How should solver.js and index.js be handled?

### ISSUE THREAD

**Issue by jambolo** [joedrago/sudokujs#15]
Tracking solver.js and index.js in git is problematic because they can't be merged. Anytime there is a merge, they must be rebuilt.  It is also possible to commit changes to the coffee files that aren't reflected in the js files.

In short, I don't think they should be tracked by git because they are not source. If that is not an option, then they need to be explicitly rebuilt and committed after any merge with a conflict.

**Comment by joedrago** [comment]
I just removed the generated `.js` files from the repo and `.gitignore`'d them. I also updated the deps, so you might want to throw away your `node_modules` dir and do a fresh `npm install`.
