### ISSUE TITLE
Left and right arrows (undo/redo) don't draw in some browsers

### ISSUE THREAD

**Issue by jambolo** [joedrago/sudokujs#9]
The left and right arrows , ⏴ (&#x23f4) and ⏵(&#x23f5), used for undo and redo are drawn in Chrome on Windows 10, but not in other browsers. It looks like maybe a font issue because a square is drawn instead.

The arrows are not drawn in Chrome on Mac and Chrome on Android.

**Comment by joedrago** [comment]
I wonder if the saxmono.ttf I'm using doesn't draw it, and whatever fallback font other browsers use also don't have them.

Perhaps we can figure out a different font that looks similar but has those glyphs and embed it insteaad.

**Comment by jambolo** [comment]
I looked at a couple sites where you can download it and https://www.fontsquirrel.com/fonts/saxMono has those glyphs, but https://www.dafont.com/saxmono.font does not. That is unexpected.

I can change them back to << and >>.
